spring.application.name=Sistema_Gestor_Empleados
spring.datasource.url=jdbc:postgresql://localhost:5432/gestor_empleados
spring.datasource.username=postgres
spring.datasource.password=mariscos
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
